# PlayerInvinciblity config.yml
invincible: [player1, player2, player3]
logInvincibleDamage: true
sendInvincibleMessage: true
broadcastInvincibleMessage: true
invincibleMessage: "You were attempted to be damaged by %player% but you are invincible!"
invincibleMessageDamager: "You attempted to damage %player% but they are invincible!"
invincibleMessageBroadcast: "%damager% attempted to damage %player% but they are invincible!"

configVersion: 1