name: PlayerInvincibility
description: Let players be invincible to other player attacks!
version: '${project.version}'
main: me.jovannmc.playerinvincibility.PlayerInvincibility
api-version: '1.13'
commands:
  playerinvincibility:
    description: PlayerInvincibility command
    aliases: [pi, invincibility]
permissions:
  playerinvincibility.*:
    description: Gives access to all PlayerInvincibility permission nodes
    default: op
    children:
      playerinvincibility.reload: true
      playerinvincibility.bypass: true
      playerinvincibility.add: true
      playerinvincibility.remove: true
  playerinvincibility.info:
    description: Use /playerinvincibility command
    default: true
  playerinvincibility.reload:
    description: Reload PlayerInvincibility
    default: op
  playerinvincibility.bypass:
    description: Bypass a player's invincibility
    default: op
  playerinvincibility.add:
    description: Add a player to the invincibility list
    default: op
  playerinvincibility.remove:
    description: Remove a player from the invincibility list
    default: op